from sqlalchemy import Index, Column, String, BIGINT, DECIMAL

from moquant.dbclient.base import Base


class StockCashFlow(Base):
    __tablename__ = 'ts_cash_flow'
    __table_args__ = (
        Index('code_date', 'ts_code', 'f_ann_date'),
        {'mysql_engine': 'InnoDB', 'mysql_charset': 'utf8'}
    )

    id = Column('id', BIGINT, primary_key=True, comment='id', autoincrement=True)
    ts_code = Column('ts_code', String(10), comment='TS股票代码')
    ann_date = Column('ann_date', String(10), comment='公告日期')
    f_ann_date = Column('f_ann_date', String(10), comment='实际公告日期')
    end_date = Column('end_date', String(10), comment='报告期')
    comp_type = Column('comp_type', String(10), comment='公司类型')
    report_type = Column('report_type', String(10), comment='报表类型')
    net_profit = Column('net_profit', DECIMAL(30, 10), comment='净利润')
    finan_exp = Column('finan_exp', DECIMAL(30, 10), comment='财务费用')
    c_fr_sale_sg = Column('c_fr_sale_sg', DECIMAL(30, 10), comment='销售商品、提供劳务收到的现金')
    recp_tax_rends = Column('recp_tax_rends', DECIMAL(30, 10), comment='收到的税费返还')
    n_depos_incr_fi = Column('n_depos_incr_fi', DECIMAL(30, 10), comment='客户存款和同业存放款项净增加额')
    n_incr_loans_cb = Column('n_incr_loans_cb', DECIMAL(30, 10), comment='向中央银行借款净增加额')
    n_inc_borr_oth_fi = Column('n_inc_borr_oth_fi', DECIMAL(30, 10), comment='向其他金融机构拆入资金净增加额')
    prem_fr_orig_contr = Column('prem_fr_orig_contr', DECIMAL(30, 10), comment='收到原保险合同保费取得的现金')
    n_incr_insured_dep = Column('n_incr_insured_dep', DECIMAL(30, 10), comment='保户储金净增加额')
    n_reinsur_prem = Column('n_reinsur_prem', DECIMAL(30, 10), comment='收到再保业务现金净额')
    n_incr_disp_tfa = Column('n_incr_disp_tfa', DECIMAL(30, 10), comment='处置交易性金融资产净增加额')
    ifc_cash_incr = Column('ifc_cash_incr', DECIMAL(30, 10), comment='收取利息和手续费净增加额')
    n_incr_disp_faas = Column('n_incr_disp_faas', DECIMAL(30, 10), comment='处置可供出售金融资产净增加额')
    n_incr_loans_oth_bank = Column('n_incr_loans_oth_bank', DECIMAL(30, 10), comment='拆入资金净增加额')
    n_cap_incr_repur = Column('n_cap_incr_repur', DECIMAL(30, 10), comment='回购业务资金净增加额')
    c_fr_oth_operate_a = Column('c_fr_oth_operate_a', DECIMAL(30, 10), comment='收到其他与经营活动有关的现金')
    c_inf_fr_operate_a = Column('c_inf_fr_operate_a', DECIMAL(30, 10), comment='经营活动现金流入小计')
    c_paid_goods_s = Column('c_paid_goods_s', DECIMAL(30, 10), comment='购买商品、接受劳务支付的现金')
    c_paid_to_for_empl = Column('c_paid_to_for_empl', DECIMAL(30, 10), comment='支付给职工以及为职工支付的现金')
    c_paid_for_taxes = Column('c_paid_for_taxes', DECIMAL(30, 10), comment='支付的各项税费')
    n_incr_clt_loan_adv = Column('n_incr_clt_loan_adv', DECIMAL(30, 10), comment='客户贷款及垫款净增加额')
    n_incr_dep_cbob = Column('n_incr_dep_cbob', DECIMAL(30, 10), comment='存放央行和同业款项净增加额')
    c_pay_claims_orig_inco = Column('c_pay_claims_orig_inco', DECIMAL(30, 10), comment='支付原保险合同赔付款项的现金')
    pay_handling_chrg = Column('pay_handling_chrg', DECIMAL(30, 10), comment='支付手续费的现金')
    pay_comm_insur_plcy = Column('pay_comm_insur_plcy', DECIMAL(30, 10), comment='支付保单红利的现金')
    oth_cash_pay_oper_act = Column('oth_cash_pay_oper_act', DECIMAL(30, 10), comment='支付其他与经营活动有关的现金')
    st_cash_out_act = Column('st_cash_out_act', DECIMAL(30, 10), comment='经营活动现金流出小计')
    n_cashflow_act = Column('n_cashflow_act', DECIMAL(30, 10), comment='经营活动产生的现金流量净额')
    oth_recp_ral_inv_act = Column('oth_recp_ral_inv_act', DECIMAL(30, 10), comment='收到其他与投资活动有关的现金')
    c_disp_withdrwl_invest = Column('c_disp_withdrwl_invest', DECIMAL(30, 10), comment='收回投资收到的现金')
    c_recp_return_invest = Column('c_recp_return_invest', DECIMAL(30, 10), comment='取得投资收益收到的现金')
    n_recp_disp_fiolta = Column('n_recp_disp_fiolta', DECIMAL(30, 10), comment='处置固定资产、无形资产和其他长期资产收回的现金净额')
    n_recp_disp_sobu = Column('n_recp_disp_sobu', DECIMAL(30, 10), comment='处置子公司及其他营业单位收到的现金净额')
    stot_inflows_inv_act = Column('stot_inflows_inv_act', DECIMAL(30, 10), comment='投资活动现金流入小计')
    c_pay_acq_const_fiolta = Column('c_pay_acq_const_fiolta', DECIMAL(30, 10), comment='购建固定资产、无形资产和其他长期资产支付的现金')
    c_paid_invest = Column('c_paid_invest', DECIMAL(30, 10), comment='投资支付的现金')
    n_disp_subs_oth_biz = Column('n_disp_subs_oth_biz', DECIMAL(30, 10), comment='取得子公司及其他营业单位支付的现金净额')
    oth_pay_ral_inv_act = Column('oth_pay_ral_inv_act', DECIMAL(30, 10), comment='支付其他与投资活动有关的现金')
    n_incr_pledge_loan = Column('n_incr_pledge_loan', DECIMAL(30, 10), comment='质押贷款净增加额')
    stot_out_inv_act = Column('stot_out_inv_act', DECIMAL(30, 10), comment='投资活动现金流出小计')
    n_cashflow_inv_act = Column('n_cashflow_inv_act', DECIMAL(30, 10), comment='投资活动产生的现金流量净额')
    c_recp_borrow = Column('c_recp_borrow', DECIMAL(30, 10), comment='取得借款收到的现金')
    proc_issue_bonds = Column('proc_issue_bonds', DECIMAL(30, 10), comment='发行债券收到的现金')
    oth_cash_recp_ral_fnc_act = Column('oth_cash_recp_ral_fnc_act', DECIMAL(30, 10), comment='收到其他与筹资活动有关的现金')
    stot_cash_in_fnc_act = Column('stot_cash_in_fnc_act', DECIMAL(30, 10), comment='筹资活动现金流入小计')
    free_cashflow = Column('free_cashflow', DECIMAL(30, 10), comment='企业自由现金流量')
    c_prepay_amt_borr = Column('c_prepay_amt_borr', DECIMAL(30, 10), comment='偿还债务支付的现金')
    c_pay_dist_dpcp_int_exp = Column('c_pay_dist_dpcp_int_exp', DECIMAL(30, 10), comment='分配股利、利润或偿付利息支付的现金')
    incl_dvd_profit_paid_sc_ms = Column('incl_dvd_profit_paid_sc_ms', DECIMAL(30, 10), comment='其中:子公司支付给少数股东的股利、利润')
    oth_cashpay_ral_fnc_act = Column('oth_cashpay_ral_fnc_act', DECIMAL(30, 10), comment='支付其他与筹资活动有关的现金')
    stot_cashout_fnc_act = Column('stot_cashout_fnc_act', DECIMAL(30, 10), comment='筹资活动现金流出小计')
    n_cash_flows_fnc_act = Column('n_cash_flows_fnc_act', DECIMAL(30, 10), comment='筹资活动产生的现金流量净额')
    eff_fx_flu_cash = Column('eff_fx_flu_cash', DECIMAL(30, 10), comment='汇率变动对现金的影响')
    n_incr_cash_cash_equ = Column('n_incr_cash_cash_equ', DECIMAL(30, 10), comment='现金及现金等价物净增加额')
    c_cash_equ_beg_period = Column('c_cash_equ_beg_period', DECIMAL(30, 10), comment='期初现金及现金等价物余额')
    c_cash_equ_end_period = Column('c_cash_equ_end_period', DECIMAL(30, 10), comment='期末现金及现金等价物余额')
    c_recp_cap_contrib = Column('c_recp_cap_contrib', DECIMAL(30, 10), comment='吸收投资收到的现金')
    incl_cash_rec_saims = Column('incl_cash_rec_saims', DECIMAL(30, 10), comment='其中:子公司吸收少数股东投资收到的现金')
    uncon_invest_loss = Column('uncon_invest_loss', DECIMAL(30, 10), comment='未确认投资损失')
    prov_depr_assets = Column('prov_depr_assets', DECIMAL(30, 10), comment='加:资产减值准备')
    depr_fa_coga_dpba = Column('depr_fa_coga_dpba', DECIMAL(30, 10), comment='固定资产折旧、油气资产折耗、生产性生物资产折旧')
    amort_intang_assets = Column('amort_intang_assets', DECIMAL(30, 10), comment='无形资产摊销')
    lt_amort_deferred_exp = Column('lt_amort_deferred_exp', DECIMAL(30, 10), comment='长期待摊费用摊销')
    decr_deferred_exp = Column('decr_deferred_exp', DECIMAL(30, 10), comment='待摊费用减少')
    incr_acc_exp = Column('incr_acc_exp', DECIMAL(30, 10), comment='预提费用增加')
    loss_disp_fiolta = Column('loss_disp_fiolta', DECIMAL(30, 10), comment='处置固定、无形资产和其他长期资产的损失')
    loss_scr_fa = Column('loss_scr_fa', DECIMAL(30, 10), comment='固定资产报废损失')
    loss_fv_chg = Column('loss_fv_chg', DECIMAL(30, 10), comment='公允价值变动损失')
    invest_loss = Column('invest_loss', DECIMAL(30, 10), comment='投资损失')
    decr_def_inc_tax_assets = Column('decr_def_inc_tax_assets', DECIMAL(30, 10), comment='递延所得税资产减少')
    incr_def_inc_tax_liab = Column('incr_def_inc_tax_liab', DECIMAL(30, 10), comment='递延所得税负债增加')
    decr_inventories = Column('decr_inventories', DECIMAL(30, 10), comment='存货的减少')
    decr_oper_payable = Column('decr_oper_payable', DECIMAL(30, 10), comment='经营性应收项目的减少')
    incr_oper_payable = Column('incr_oper_payable', DECIMAL(30, 10), comment='经营性应付项目的增加')
    others = Column('others', DECIMAL(30, 10), comment='其他')
    im_net_cashflow_oper_act = Column('im_net_cashflow_oper_act', DECIMAL(30, 10), comment='经营活动产生的现金流量净额(间接法)')
    conv_debt_into_cap = Column('conv_debt_into_cap', DECIMAL(30, 10), comment='债务转为资本')
    conv_copbonds_due_within_1y = Column('conv_copbonds_due_within_1y', DECIMAL(30, 10), comment='一年内到期的可转换公司债券')
    fa_fnc_leases = Column('fa_fnc_leases', DECIMAL(30, 10), comment='融资租入固定资产')
    end_bal_cash = Column('end_bal_cash', DECIMAL(30, 10), comment='现金的期末余额')
    beg_bal_cash = Column('beg_bal_cash', DECIMAL(30, 10), comment='减:现金的期初余额')
    end_bal_cash_equ = Column('end_bal_cash_equ', DECIMAL(30, 10), comment='加:现金等价物的期末余额')
    beg_bal_cash_equ = Column('beg_bal_cash_equ', DECIMAL(30, 10), comment='减:现金等价物的期初余额')
    im_n_incr_cash_equ = Column('im_n_incr_cash_equ', DECIMAL(30, 10), comment='现金及现金等价物净增加额(间接法)')
    update_flag = Column('update_flag', String(10), comment='更新标识')
