from sqlalchemy import Column, BIGINT, Index, String, DECIMAL, INT

from moquant.dbclient.base import Base


class TsFinaIndicator(Base):
    __tablename__ = 'ts_fina_indicator'
    __table_args__ = (
        Index('code_date', 'ts_code', 'ann_date', 'end_date'),
        Index('code_period', 'ts_code', 'end_date'),
        {'mysql_engine': 'InnoDB', 'mysql_charset': 'utf8'}
    )

    id = Column('id', BIGINT, primary_key=True, comment='id', autoincrement=True)
    ts_code = Column('ts_code', String(10), comment='TS代码')
    ann_date = Column('ann_date', String(10), comment='公告日期')
    end_date = Column('end_date', String(10), comment='报告期')
    eps = Column('eps', DECIMAL(30, 10), comment='基本每股收益')
    dt_eps = Column('dt_eps', DECIMAL(30, 10), comment='稀释每股收益')
    total_revenue_ps = Column('total_revenue_ps', DECIMAL(30, 10), comment='每股营业总收入')
    revenue_ps = Column('revenue_ps', DECIMAL(30, 10), comment='每股营业收入')
    capital_rese_ps = Column('capital_rese_ps', DECIMAL(30, 10), comment='每股资本公积')
    surplus_rese_ps = Column('surplus_rese_ps', DECIMAL(30, 10), comment='每股盈余公积')
    undist_profit_ps = Column('undist_profit_ps', DECIMAL(30, 10), comment='每股未分配利润')
    extra_item = Column('extra_item', DECIMAL(30, 10), comment='非经常性损益')
    profit_dedt = Column('profit_dedt', DECIMAL(30, 10), comment='扣除非经常性损益后的净利润')
    gross_margin = Column('gross_margin', DECIMAL(30, 10), comment='毛利')
    current_ratio = Column('current_ratio', DECIMAL(30, 10), comment='流动比率')
    quick_ratio = Column('quick_ratio', DECIMAL(30, 10), comment='速动比率')
    cash_ratio = Column('cash_ratio', DECIMAL(30, 10), comment='保守速动比率')
    invturn_days = Column('invturn_days', DECIMAL(30, 10), comment='存货周转天数')
    arturn_days = Column('arturn_days', DECIMAL(30, 10), comment='应收账款周转天数')
    inv_turn = Column('inv_turn', DECIMAL(30, 10), comment='存货周转率')
    ar_turn = Column('ar_turn', DECIMAL(30, 10), comment='应收账款周转率')
    ca_turn = Column('ca_turn', DECIMAL(30, 10), comment='流动资产周转率')
    fa_turn = Column('fa_turn', DECIMAL(30, 10), comment='固定资产周转率')
    assets_turn = Column('assets_turn', DECIMAL(30, 10), comment='总资产周转率')
    op_income = Column('op_income', DECIMAL(30, 10), comment='经营活动净收益')
    valuechange_income = Column('valuechange_income', DECIMAL(30, 10), comment='价值变动净收益')
    interst_income = Column('interst_income', DECIMAL(30, 10), comment='利息费用')
    daa = Column('daa', DECIMAL(30, 10), comment='折旧与摊销')
    ebit = Column('ebit', DECIMAL(30, 10), comment='息税前利润')
    ebitda = Column('ebitda', DECIMAL(30, 10), comment='息税折旧摊销前利润')
    fcff = Column('fcff', DECIMAL(30, 10), comment='企业自由现金流量')
    fcfe = Column('fcfe', DECIMAL(30, 10), comment='股权自由现金流量')
    current_exint = Column('current_exint', DECIMAL(30, 10), comment='无息流动负债')
    noncurrent_exint = Column('noncurrent_exint', DECIMAL(30, 10), comment='无息非流动负债')
    interestdebt = Column('interestdebt', DECIMAL(30, 10), comment='带息债务')
    netdebt = Column('netdebt', DECIMAL(30, 10), comment='净债务')
    tangible_asset = Column('tangible_asset', DECIMAL(30, 10), comment='有形资产')
    working_capital = Column('working_capital', DECIMAL(30, 10), comment='营运资金')
    networking_capital = Column('networking_capital', DECIMAL(30, 10), comment='营运流动资本')
    invest_capital = Column('invest_capital', DECIMAL(30, 10), comment='全部投入资本')
    retained_earnings = Column('retained_earnings', DECIMAL(30, 10), comment='留存收益')
    diluted2_eps = Column('diluted2_eps', DECIMAL(30, 10), comment='期末摊薄每股收益')
    bps = Column('bps', DECIMAL(30, 10), comment='每股净资产')
    ocfps = Column('ocfps', DECIMAL(30, 10), comment='每股经营活动产生的现金流量净额')
    retainedps = Column('retainedps', DECIMAL(30, 10), comment='每股留存收益')
    cfps = Column('cfps', DECIMAL(30, 10), comment='每股现金流量净额')
    ebit_ps = Column('ebit_ps', DECIMAL(30, 10), comment='每股息税前利润')
    fcff_ps = Column('fcff_ps', DECIMAL(30, 10), comment='每股企业自由现金流量')
    fcfe_ps = Column('fcfe_ps', DECIMAL(30, 10), comment='每股股东自由现金流量')
    netprofit_margin = Column('netprofit_margin', DECIMAL(30, 10), comment='销售净利率')
    grossprofit_margin = Column('grossprofit_margin', DECIMAL(30, 10), comment='销售毛利率')
    cogs_of_sales = Column('cogs_of_sales', DECIMAL(30, 10), comment='销售成本率')
    expense_of_sales = Column('expense_of_sales', DECIMAL(30, 10), comment='销售期间费用率')
    profit_to_gr = Column('profit_to_gr', DECIMAL(30, 10), comment='净利润/营业总收入')
    saleexp_to_gr = Column('saleexp_to_gr', DECIMAL(30, 10), comment='销售费用/营业总收入')
    adminexp_of_gr = Column('adminexp_of_gr', DECIMAL(30, 10), comment='管理费用/营业总收入')
    finaexp_of_gr = Column('finaexp_of_gr', DECIMAL(30, 10), comment='财务费用/营业总收入')
    impai_ttm = Column('impai_ttm', DECIMAL(30, 10), comment='资产减值损失/营业总收入')
    gc_of_gr = Column('gc_of_gr', DECIMAL(30, 10), comment='营业总成本/营业总收入')
    op_of_gr = Column('op_of_gr', DECIMAL(30, 10), comment='营业利润/营业总收入')
    ebit_of_gr = Column('ebit_of_gr', DECIMAL(30, 10), comment='息税前利润/营业总收入')
    roe = Column('roe', DECIMAL(30, 10), comment='净资产收益率')
    roe_waa = Column('roe_waa', DECIMAL(30, 10), comment='加权平均净资产收益率')
    roe_dt = Column('roe_dt', DECIMAL(30, 10), comment='净资产收益率(扣除非经常损益)')
    roa = Column('roa', DECIMAL(30, 10), comment='总资产报酬率')
    npta = Column('npta', DECIMAL(30, 10), comment='总资产净利润')
    roic = Column('roic', DECIMAL(30, 10), comment='投入资本回报率')
    roe_yearly = Column('roe_yearly', DECIMAL(30, 10), comment='年化净资产收益率')
    roa2_yearly = Column('roa2_yearly', DECIMAL(30, 10), comment='年化总资产报酬率')
    roe_avg = Column('roe_avg', DECIMAL(30, 10), comment='平均净资产收益率(增发条件)')
    opincome_of_ebt = Column('opincome_of_ebt', DECIMAL(30, 10), comment='经营活动净收益/利润总额')
    investincome_of_ebt = Column('investincome_of_ebt', DECIMAL(30, 10), comment='价值变动净收益/利润总额')
    n_op_profit_of_ebt = Column('n_op_profit_of_ebt', DECIMAL(30, 10), comment='营业外收支净额/利润总额')
    tax_to_ebt = Column('tax_to_ebt', DECIMAL(30, 10), comment='所得税/利润总额')
    dtprofit_to_profit = Column('dtprofit_to_profit', DECIMAL(30, 10), comment='扣除非经常损益后的净利润/净利润')
    salescash_to_or = Column('salescash_to_or', DECIMAL(30, 10), comment='销售商品提供劳务收到的现金/营业收入')
    ocf_to_or = Column('ocf_to_or', DECIMAL(30, 10), comment='经营活动产生的现金流量净额/营业收入')
    ocf_to_opincome = Column('ocf_to_opincome', DECIMAL(30, 10), comment='经营活动产生的现金流量净额/经营活动净收益')
    capitalized_to_da = Column('capitalized_to_da', DECIMAL(30, 10), comment='资本支出/折旧和摊销')
    debt_to_assets = Column('debt_to_assets', DECIMAL(30, 10), comment='资产负债率')
    assets_to_eqt = Column('assets_to_eqt', DECIMAL(30, 10), comment='权益乘数')
    dp_assets_to_eqt = Column('dp_assets_to_eqt', DECIMAL(30, 10), comment='权益乘数(杜邦分析)')
    ca_to_assets = Column('ca_to_assets', DECIMAL(30, 10), comment='流动资产/总资产')
    nca_to_assets = Column('nca_to_assets', DECIMAL(30, 10), comment='非流动资产/总资产')
    tbassets_to_totalassets = Column('tbassets_to_totalassets', DECIMAL(30, 10), comment='有形资产/总资产')
    int_to_talcap = Column('int_to_talcap', DECIMAL(30, 10), comment='带息债务/全部投入资本')
    eqt_to_talcapital = Column('eqt_to_talcapital', DECIMAL(30, 10), comment='归属于母公司的股东权益/全部投入资本')
    currentdebt_to_debt = Column('currentdebt_to_debt', DECIMAL(30, 10), comment='流动负债/负债合计')
    longdeb_to_debt = Column('longdeb_to_debt', DECIMAL(30, 10), comment='非流动负债/负债合计')
    ocf_to_shortdebt = Column('ocf_to_shortdebt', DECIMAL(30, 10), comment='经营活动产生的现金流量净额/流动负债')
    debt_to_eqt = Column('debt_to_eqt', DECIMAL(30, 10), comment='产权比率')
    eqt_to_debt = Column('eqt_to_debt', DECIMAL(30, 10), comment='归属于母公司的股东权益/负债合计')
    eqt_to_interestdebt = Column('eqt_to_interestdebt', DECIMAL(30, 10), comment='归属于母公司的股东权益/带息债务')
    tangibleasset_to_debt = Column('tangibleasset_to_debt', DECIMAL(30, 10), comment='有形资产/负债合计')
    tangasset_to_intdebt = Column('tangasset_to_intdebt', DECIMAL(30, 10), comment='有形资产/带息债务')
    tangibleasset_to_netdebt = Column('tangibleasset_to_netdebt', DECIMAL(30, 10), comment='有形资产/净债务')
    ocf_to_debt = Column('ocf_to_debt', DECIMAL(30, 10), comment='经营活动产生的现金流量净额/负债合计')
    ocf_to_interestdebt = Column('ocf_to_interestdebt', DECIMAL(30, 10), comment='经营活动产生的现金流量净额/带息债务')
    ocf_to_netdebt = Column('ocf_to_netdebt', DECIMAL(30, 10), comment='经营活动产生的现金流量净额/净债务')
    ebit_to_interest = Column('ebit_to_interest', DECIMAL(30, 10), comment='已获利息倍数(EBIT/利息费用)')
    longdebt_to_workingcapital = Column('longdebt_to_workingcapital', DECIMAL(30, 10), comment='长期债务与营运资金比率')
    ebitda_to_debt = Column('ebitda_to_debt', DECIMAL(30, 10), comment='息税折旧摊销前利润/负债合计')
    turn_days = Column('turn_days', DECIMAL(30, 10), comment='营业周期')
    roa_yearly = Column('roa_yearly', DECIMAL(30, 10), comment='年化总资产净利率')
    roa_dp = Column('roa_dp', DECIMAL(30, 10), comment='总资产净利率(杜邦分析)')
    fixed_assets = Column('fixed_assets', DECIMAL(30, 10), comment='固定资产合计')
    profit_prefin_exp = Column('profit_prefin_exp', DECIMAL(30, 10), comment='扣除财务费用前营业利润')
    non_op_profit = Column('non_op_profit', DECIMAL(30, 10), comment='非营业利润')
    op_to_ebt = Column('op_to_ebt', DECIMAL(30, 10), comment='营业利润／利润总额')
    nop_to_ebt = Column('nop_to_ebt', DECIMAL(30, 10), comment='非营业利润／利润总额')
    ocf_to_profit = Column('ocf_to_profit', DECIMAL(30, 10), comment='经营活动产生的现金流量净额／营业利润')
    cash_to_liqdebt = Column('cash_to_liqdebt', DECIMAL(30, 10), comment='货币资金／流动负债')
    cash_to_liqdebt_withinterest = Column('cash_to_liqdebt_withinterest', DECIMAL(30, 10), comment='货币资金／带息流动负债')
    op_to_liqdebt = Column('op_to_liqdebt', DECIMAL(30, 10), comment='营业利润／流动负债')
    op_to_debt = Column('op_to_debt', DECIMAL(30, 10), comment='营业利润／负债合计')
    roic_yearly = Column('roic_yearly', DECIMAL(30, 10), comment='年化投入资本回报率')
    total_fa_trun = Column('total_fa_trun', DECIMAL(30, 10), comment='固定资产合计周转率')
    profit_to_op = Column('profit_to_op', DECIMAL(30, 10), comment='利润总额／营业收入')
    q_opincome = Column('q_opincome', DECIMAL(30, 10), comment='经营活动单季度净收益')
    q_investincome = Column('q_investincome', DECIMAL(30, 10), comment='价值变动单季度净收益')
    q_dtprofit = Column('q_dtprofit', DECIMAL(30, 10), comment='扣除非经常损益后的单季度净利润')
    q_eps = Column('q_eps', DECIMAL(30, 10), comment='每股收益(单季度)')
    q_netprofit_margin = Column('q_netprofit_margin', DECIMAL(30, 10), comment='销售净利率(单季度)')
    q_gsprofit_margin = Column('q_gsprofit_margin', DECIMAL(30, 10), comment='销售毛利率(单季度)')
    q_exp_to_sales = Column('q_exp_to_sales', DECIMAL(30, 10), comment='销售期间费用率(单季度)')
    q_profit_to_gr = Column('q_profit_to_gr', DECIMAL(30, 10), comment='净利润／营业总收入(单季度)')
    q_saleexp_to_gr = Column('q_saleexp_to_gr', DECIMAL(30, 10), comment='销售费用／营业总收入 (单季度)')
    q_adminexp_to_gr = Column('q_adminexp_to_gr', DECIMAL(30, 10), comment='管理费用／营业总收入 (单季度)')
    q_finaexp_to_gr = Column('q_finaexp_to_gr', DECIMAL(30, 10), comment='财务费用／营业总收入 (单季度)')
    q_impair_to_gr_ttm = Column('q_impair_to_gr_ttm', DECIMAL(30, 10), comment='资产减值损失／营业总收入(单季度)')
    q_gc_to_gr = Column('q_gc_to_gr', DECIMAL(30, 10), comment='营业总成本／营业总收入 (单季度)')
    q_op_to_gr = Column('q_op_to_gr', DECIMAL(30, 10), comment='营业利润／营业总收入(单季度)')
    q_roe = Column('q_roe', DECIMAL(30, 10), comment='净资产收益率(单季度)')
    q_dt_roe = Column('q_dt_roe', DECIMAL(30, 10), comment='净资产单季度收益率(扣除非经常损益)')
    q_npta = Column('q_npta', DECIMAL(30, 10), comment='总资产净利润(单季度)')
    q_opincome_to_ebt = Column('q_opincome_to_ebt', DECIMAL(30, 10), comment='经营活动净收益／利润总额(单季度)')
    q_investincome_to_ebt = Column('q_investincome_to_ebt', DECIMAL(30, 10), comment='价值变动净收益／利润总额(单季度)')
    q_dtprofit_to_profit = Column('q_dtprofit_to_profit', DECIMAL(30, 10), comment='扣除非经常损益后的净利润／净利润(单季度)')
    q_salescash_to_or = Column('q_salescash_to_or', DECIMAL(30, 10), comment='销售商品提供劳务收到的现金／营业收入(单季度)')
    q_ocf_to_sales = Column('q_ocf_to_sales', DECIMAL(30, 10), comment='经营活动产生的现金流量净额／营业收入(单季度)')
    q_ocf_to_or = Column('q_ocf_to_or', DECIMAL(30, 10), comment='经营活动产生的现金流量净额／经营活动净收益(单季度)')
    basic_eps_yoy = Column('basic_eps_yoy', DECIMAL(30, 10), comment='基本每股收益同比增长率(%)')
    dt_eps_yoy = Column('dt_eps_yoy', DECIMAL(30, 10), comment='稀释每股收益同比增长率(%)')
    cfps_yoy = Column('cfps_yoy', DECIMAL(30, 10), comment='每股经营活动产生的现金流量净额同比增长率(%)')
    op_yoy = Column('op_yoy', DECIMAL(30, 10), comment='营业利润同比增长率(%)')
    ebt_yoy = Column('ebt_yoy', DECIMAL(30, 10), comment='利润总额同比增长率(%)')
    netprofit_yoy = Column('netprofit_yoy', DECIMAL(30, 10), comment='归属母公司股东的净利润同比增长率(%)')
    dt_netprofit_yoy = Column('dt_netprofit_yoy', DECIMAL(30, 10), comment='归属母公司股东的净利润-扣除非经常损益同比增长率(%)')
    ocf_yoy = Column('ocf_yoy', DECIMAL(30, 10), comment='经营活动产生的现金流量净额同比增长率(%)')
    roe_yoy = Column('roe_yoy', DECIMAL(30, 10), comment='净资产收益率(摊薄)同比增长率(%)')
    bps_yoy = Column('bps_yoy', DECIMAL(30, 10), comment='每股净资产相对年初增长率(%)')
    assets_yoy = Column('assets_yoy', DECIMAL(30, 10), comment='资产总计相对年初增长率(%)')
    eqt_yoy = Column('eqt_yoy', DECIMAL(30, 10), comment='归属母公司的股东权益相对年初增长率(%)')
    tr_yoy = Column('tr_yoy', DECIMAL(30, 10), comment='营业总收入同比增长率(%)')
    or_yoy = Column('or_yoy', DECIMAL(30, 10), comment='营业收入同比增长率(%)')
    q_gr_yoy = Column('q_gr_yoy', DECIMAL(30, 10), comment='营业总收入同比增长率(%)(单季度)')
    q_gr_qoq = Column('q_gr_qoq', DECIMAL(30, 10), comment='营业总收入环比增长率(%)(单季度)')
    q_sales_yoy = Column('q_sales_yoy', DECIMAL(30, 10), comment='营业收入同比增长率(%)(单季度)')
    q_sales_qoq = Column('q_sales_qoq', DECIMAL(30, 10), comment='营业收入环比增长率(%)(单季度)')
    q_op_yoy = Column('q_op_yoy', DECIMAL(30, 10), comment='营业利润同比增长率(%)(单季度)')
    q_op_qoq = Column('q_op_qoq', DECIMAL(30, 10), comment='营业利润环比增长率(%)(单季度)')
    q_profit_yoy = Column('q_profit_yoy', DECIMAL(30, 10), comment='净利润同比增长率(%)(单季度)')
    q_profit_qoq = Column('q_profit_qoq', DECIMAL(30, 10), comment='净利润环比增长率(%)(单季度)')
    q_netprofit_yoy = Column('q_netprofit_yoy', DECIMAL(30, 10), comment='归属母公司股东的净利润同比增长率(%)(单季度)')
    q_netprofit_qoq = Column('q_netprofit_qoq', DECIMAL(30, 10), comment='归属母公司股东的净利润环比增长率(%)(单季度)')
    equity_yoy = Column('equity_yoy', DECIMAL(30, 10), comment='净资产同比增长率')
    rd_exp = Column('rd_exp', DECIMAL(30, 10), comment='研发费用')
    update_flag = Column('update_flag', String(10), comment='更新标识')
