package com.cn.momojie.moquant.api.dto;

public class MqSysParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_sys_param.key
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_sys_param.value
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mq_sys_param.remark
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_sys_param.key
     *
     * @return the value of mq_sys_param.key
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_sys_param.key
     *
     * @param key the value for mq_sys_param.key
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_sys_param.value
     *
     * @return the value of mq_sys_param.value
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_sys_param.value
     *
     * @param value the value for mq_sys_param.value
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mq_sys_param.remark
     *
     * @return the value of mq_sys_param.remark
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mq_sys_param.remark
     *
     * @param remark the value for mq_sys_param.remark
     *
     * @mbg.generated Fri Oct 04 15:04:31 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}